name: 'LocalStack Preview'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  localstack:
    name: Setup LocalStack Preview
    runs-on: ubuntu-latest
    steps:
      - name: LocalStack Preview
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: ephemeral
          state-action: start
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
