name: 'Creat Preview on Push'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  localstack:
    name: Setup LocalStack Preview
    runs-on: ubuntu-latest
    steps:
      - name: LocalStack Preview
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: ephemeral
          state-action: start
          install-awslocal: 'true'
          preview-cmd: |
            awslocal bootstrap
            awslocal deploy
            echo LS_PREVIEW_URL=$AWS_ENDPOINT_URL/cloudfront/$distributionId/ >> $GITHUB_ENV;
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
